source 'http://rubygems.org'
source 'http://gems.github.com'

gem 'rails', '3.1'
gem 'pg'
gem 'nokogiri'
gem 'curb'
gem 'sax-machine', :git => 'https://github.com/pauldix/sax-machine.git'
gem 'loofah-activerecord'
#gem 'paperclip'
#gem 'devise'
#gem 'rails_admin', :git => 'git://github.com/sferik/rails_admin.git'
gem 'summarize'
#gem 'acts-as-taggable-on'
#gem 'wtf_lang'
#gem 'to_lang'